import { TOPIC_PREFIX } from "@/shared/utils";

export const tags = [
  `${TOPIC_PREFIX}health-&-wellness`,
  `${TOPIC_PREFIX}technology`,
  `${TOPIC_PREFIX}travel-&-adventure`,
  `${TOPIC_PREFIX}entertainment`,
  `${TOPIC_PREFIX}business-&-finance`,
  `${TOPIC_PREFIX}food-&-cooking`,
  `${TOPIC_PREFIX}personal-development`,
  `${TOPIC_PREFIX}science`,
  `${TOPIC_PREFIX}sports`,
  `${TOPIC_PREFIX}art-&-creativity`,
  `${TOPIC_PREFIX}fashion`,
  `${TOPIC_PREFIX}environment`,
  `${TOPIC_PREFIX}education`,
  `${TOPIC_PREFIX}philosophy`,
  `${TOPIC_PREFIX}social-media`,
  `${TOPIC_PREFIX}programming`,
  `${TOPIC_PREFIX}gaming`,
  `${TOPIC_PREFIX}photography`,
  `${TOPIC_PREFIX}literature`,
  `${TOPIC_PREFIX}music`,
  `${TOPIC_PREFIX}film`,
  `${TOPIC_PREFIX}design`,
  `${TOPIC_PREFIX}entrepreneurship`,
  `${TOPIC_PREFIX}mindfulness`,
  `${TOPIC_PREFIX}psychology`,
  `${TOPIC_PREFIX}sustainability`,
  `${TOPIC_PREFIX}history`,
  `${TOPIC_PREFIX}astronomy`,
  `${TOPIC_PREFIX}fitness`,
  `${TOPIC_PREFIX}diy-crafts`,
];
