schema: "src/graphql/schema/**/*.graphqls"
documents: "**/*.graphql"
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
config:
  avoidOptionals: false
  maybeValue: T
