schema: "src/graphql/schema/**/*.graphqls"
documents:
  - "**/*.graphql"
  - "!node_modules/**/*"
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
config:
  avoidOptionals: false
  maybeValue: T
