schema: "src/graphql/schema/**/*.graphqls"
documents:
  - "src/graphql/**/*.graphql"
plugins:
  - typescript-operations
  # - typescript-react-apollo
  - typescript-urql
  - add
cacheDir: __generated__
config:
  avoidOptionals: false
  maybeValue: T
  withComponent: false
  withHooks: true
  # skipTypename: false
  content: "//@ts-nocheck"
