schema: "src/graphql/schema/**/*.graphqls"
documents:
  - "src/graphql/**/*.graphql"
plugins:
  - typescript-operations
  # - typescript-react-apollo
  - typescript-urql
cacheDir: __generated__
config:
  avoidOptionals: false
  # maybeValue: T
