schema: "src/graphql/schema/**/*.graphqls"
documents:
  - "src/graphql/**/*.graphql"
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
config:
  avoidOptionals: false
  maybeValue: T
