/* 3e7074dc8a5eded674e0422b501bcff6afcad920
 * This file is automatically generated by graphql-let. */

import * as Types from '../../../__types__';

import { gql } from '@apollo/client';
export type PartialFragment = (
  { __typename?: 'Post' }
  & Pick<Types.Post, 'id' | 'title' | 'html' | 'excerpt' | 'featured' | 'html_draft' | 'type' | 'slug' | 'status' | 'createdAt' | 'publishedAt' | 'scheduledAt' | 'updatedAt' | 'reading_time'>
  & { cover_image: (
    { __typename?: 'Image' }
    & Pick<Types.Image, 'src' | 'width' | 'height'>
  ) }
);

export type PostWithAuthorAndTagsFragment = (
  { __typename?: 'Post' }
  & { author?: Types.Maybe<(
    { __typename?: 'Author' }
    & Pick<Types.Author, 'id' | 'name' | 'avatar' | 'bio' | 'occupation' | 'company_name'>
    & { social?: Types.Maybe<(
      { __typename?: 'Social' }
      & Pick<Types.Social, 'github' | 'twitter' | 'instagram' | 'linkedin' | 'facebook'>
    )> }
  )>, tags?: Types.Maybe<Array<(
    { __typename?: 'Tags' }
    & Pick<Types.Tags, 'name' | 'slug'>
  )>> }
  & PartialFragment
);

export type SettingsFragmentFragment = (
  { __typename?: 'Setting' }
  & Pick<Types.Setting, 'site_title' | 'site_tagline' | 'site_email' | 'site_url' | 'site_footer' | 'site_description' | 'subscribe_embed' | 'social_twitter' | 'social_facebook' | 'social_instagram' | 'social_github' | 'display_author_info' | 'cloudinary_key' | 'cloudinary_name' | 'cloudinary_secret' | 'client_token' | 'intro_dismissed' | 'show_about_page' | 'show_tags_page' | 'css' | 'google_analytics' | 'theme'>
  & { menu: Array<(
    { __typename?: 'Navigation' }
    & Pick<Types.Navigation, 'label' | 'original_name' | 'slug' | 'type'>
  )>, analytics?: Types.Maybe<(
    { __typename?: 'Analytics' }
    & Pick<Types.Analytics, 'google_analytics' | 'umami_id' | 'simple_analytics' | 'plausible_data_domain'>
  )>, banner?: Types.Maybe<(
    { __typename?: 'Image' }
    & Pick<Types.Image, 'src' | 'width' | 'height'>
  )>, site_logo?: Types.Maybe<(
    { __typename?: 'Image' }
    & Pick<Types.Image, 'src' | 'width' | 'height'>
  )>, site_favicon?: Types.Maybe<(
    { __typename?: 'Image' }
    & Pick<Types.Image, 'src' | 'width' | 'height'>
  )> }
);

export type MeFragmentFragment = (
  { __typename?: 'Author' }
  & Pick<Types.Author, 'id' | 'name' | 'username' | 'analytics_id' | 'analytics_uuid' | 'email' | 'bio' | 'occupation' | 'company_name' | 'avatar'>
  & { social?: Types.Maybe<(
    { __typename?: 'Social' }
    & Pick<Types.Social, 'github' | 'twitter' | 'instagram' | 'facebook' | 'linkedin'>
  )> }
);

export const PartialFragmentDoc = gql`
    fragment Partial on Post {
  id
  title
  html
  excerpt
  featured
  html_draft
  type
  slug
  status
  createdAt
  publishedAt
  scheduledAt
  updatedAt
  reading_time
  cover_image {
    src
    width
    height
  }
}
    `;
export const PostWithAuthorAndTagsFragmentDoc = gql`
    fragment PostWithAuthorAndTags on Post {
  ...Partial
  author {
    id
    name
    avatar
    social {
      github
      twitter
      instagram
      linkedin
      facebook
    }
    bio
    occupation
    company_name
  }
  tags {
    name
    slug
  }
}
    ${PartialFragmentDoc}`;
export const SettingsFragmentFragmentDoc = gql`
    fragment SettingsFragment on Setting {
  site_title
  site_tagline
  site_email
  site_url
  site_footer
  site_description
  subscribe_embed
  social_twitter
  social_facebook
  social_instagram
  social_github
  display_author_info
  cloudinary_key
  cloudinary_name
  cloudinary_secret
  client_token
  intro_dismissed
  show_about_page
  show_tags_page
  menu {
    label
    original_name
    slug
    type
  }
  analytics {
    google_analytics
    umami_id
    simple_analytics
    plausible_data_domain
  }
  css
  google_analytics
  theme
  banner {
    src
    width
    height
  }
  site_logo {
    src
    width
    height
  }
  site_favicon {
    src
    width
    height
  }
}
    `;
export const MeFragmentFragmentDoc = gql`
    fragment MeFragment on Author {
  id
  name
  username
  analytics_id
  analytics_uuid
  social {
    github
    twitter
    instagram
    facebook
    linkedin
  }
  email
  bio
  occupation
  company_name
  avatar
}
    `;