module.exports = {
    GET_DB_POSTS: 'GET_DB_POSTS',
    REQUEST_DB_POSTS: 'REQUEST_DB_POSTS',
    GET_DB_SINGLE_POST: 'GET_DB_SINGLE_POST',
    REQUEST_COMMENTS: 'REQUEST_COMMENTS',
    GET_COMMENTS: 'GET_COMMENTS',
    LAZY_LOADED: 'LAZY_LOADED',
}
