const DATA = [
  {
    id: 1,
    name: "menu.allPosts",
    priority: 1,
    permissions: [],
    slug: "posts",
    icon: "fa-envelope",
  },
  {
    id: 1,
    name: "menu.allPages",
    priority: 1,
    permissions: [],
    slug: "pages",
    icon: "fa-copy",
  },
  {
    id: 3,
    name: "menu.media",
    priority: 3,
    permissions: ["MANAGE_OWN_POSTS", "MANAGE_ALL_POSTS"],
    slug: "media",
    icon: "fa-picture-o",
  },
  {
    id: 3,
    name: "menu.tags",
    priority: 3,
    permissions: ["MANAGE_OWN_POSTS", "MANAGE_ALL_POSTS"],
    slug: "tags",
    icon: "fa-tag",
  },
  {
    id: 4,
    name: "menu.categories",
    priority: 4,
    permissions: ["MANAGE_OWN_POSTS", "MANAGE_ALL_POSTS"],
    slug: "categories",
    icon: "fa-th",
  },
  {
    spacer: true,
  },
  {
    id: 6,
    name: "menu.profile",
    priority: 3,
    permissions: ["MANAGE_OWN_POSTS"],
    slug: "edit-profile",
    icon: "fa-user",
  },
  {
    id: 7,
    name: "menu.authors",
    priority: 3,
    permissions: ["MANAGE_USERS"],
    slug: "authors",
    icon: "fa-users",
  },
  {
    id: 5,
    name: "menu.sitesettings",
    priority: 3,
    permissions: ["MANAGE_SETTINGS"],
    slug: "settings",
    icon: "fa-user",
  },
  {
    id: 4,
    name: "menu.navigation",
    priority: 3,
    permissions: ["MANAGE_SETTINGS"],
    slug: "navigation-builder",
    icon: "fa-bars",
  },
];

export default DATA;
