name: Docker
on:
  push:
    branches-ignore:
      - "master"

jobs:
  job_one:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build the theme Docker Image
        run: |
          docker build . --tag ghcr.io/letterpad/letterpad-admin:latest
          docker push ghcr.io/letterpad/letterpad-admin:latest
